import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(resolve(process.env.PLAYWRIGHT_MODULE)).href : 'playwright');
const browser = await chromium.launch({ ...(process.env.GPU_TEST_BROWSER ? { executablePath: process.env.GPU_TEST_BROWSER } : process.platform === 'win32' ? { channel: 'msedge' } : {}), headless: true, args: ['--enable-unsafe-webgpu'] });
const base = process.env.PLAYGROUND_URL ?? 'http://127.0.0.1:4175/playground/';
const out = resolve('.test-dist/runtime-overlay'); await mkdir(out, { recursive: true });
try {
 const loading = await browser.newPage({ viewport: { width: 1277, height: 920 } });
 await loading.addInitScript(() => {
  const gpu = navigator.gpu;
  const original = gpu.requestAdapter.bind(gpu);
  gpu.requestAdapter = async (...args) => { await new Promise(resolve => setTimeout(resolve, 1500)); return original(...args); };
 });
 await loading.goto(base + '?example=minimal-frame&panel=code');
 await loading.locator('[data-status-preview]').waitFor();
 const overlayColor = await loading.locator('[data-status-preview]').evaluate(el => getComputedStyle(el).color);
 await loading.locator('[data-theme-mode=light]').click();
 assert.equal(await loading.locator('[data-status-preview]').evaluate(el => getComputedStyle(el).color), overlayColor, 'dark overlay stays readable in the light theme');
 assert.equal(await loading.locator('.demo-card > [data-example-feedback]').count(), 0);
 const intro = await loading.locator('.example-intro').boundingBox();
 await loading.screenshot({ path: resolve(out, 'loading.png') });
 await loading.waitForFunction(() => document.querySelector('[data-playground]').dataset.effectState === 'ready');
 assert.equal(await loading.locator('.runtime-status').isVisible(), false);
 assert.deepEqual(await loading.locator('.example-intro').boundingBox(), intro);
 await loading.goto(base + '?example=gpu-timing&panel=code');
 await loading.waitForFunction(() => document.querySelector('[data-playground]').dataset.effectState === 'ready');
 assert.equal(await loading.locator('.runtime-status').isVisible(), true, 'result or unsupported timing warning appears in Code too');
 assert.match(await loading.locator('[data-status-preview]').textContent(), /GPU time|GPU timing/);
 await loading.close();
 const error = await browser.newPage({ viewport: { width: 390, height: 844 } });
 await error.addInitScript(() => { navigator.gpu.requestAdapter = async () => { throw new Error('Unable to initialize the example. '.repeat(24)); }; });
 await error.goto(base + '?example=minimal-frame&panel=code');
 await error.waitForFunction(() => document.querySelector('[data-playground]').dataset.effectState === 'error');
 assert.equal(await error.locator('.runtime-status').getAttribute('open'), null);
 await error.locator('.runtime-status summary').focus(); await error.keyboard.press('Enter');
 assert.equal(await error.locator('[data-example-feedback]').isVisible(), true);
 assert.ok(await error.locator('[data-example-feedback]').evaluate(el => el.scrollHeight > el.clientHeight));
 const stage = await error.locator('.demo-stage').boundingBox();
 const overlay = await error.locator('.runtime-status').boundingBox();
 assert.ok(overlay.x >= stage.x && overlay.y >= stage.y && overlay.x + overlay.width <= stage.x + stage.width && overlay.y + overlay.height <= stage.y + stage.height);
 assert.ok(await error.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
 await error.screenshot({ path: resolve(out, 'mobile-error.png') });
 await error.keyboard.press('Space');
 assert.equal(await error.locator('[data-example-feedback]').isVisible(), false);
 await error.close();
 console.log('Runtime overlay: loading, result, long error, keyboard and stable layout passed');
} finally { await browser.close(); }
