import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { Window, type HTMLButtonElement, type HTMLElement } from 'happy-dom';
import { installHomeLanguage } from '../src/language.ts';
import { renderSiteFooter, renderSiteHeader } from '../shared/shell/template.ts';

test('Home language updates content, shared navigation, metadata and accessible labels', t => {
	const window = new Window();
	const originals = ['window', 'document'].map(key => [key, Object.getOwnPropertyDescriptor(globalThis, key)] as const);
	Object.defineProperty(globalThis, 'window', { value: window, configurable: true });
	Object.defineProperty(globalThis, 'document', { value: window.document, configurable: true });
	window.document.write(readFileSync('apps/site/index.html', 'utf8').replace('<!-- site-header:home -->', renderSiteHeader('home')).replace('<!-- site-footer:home -->', renderSiteFooter('home')));
	window.document.documentElement.lang = 'en';
	const language = installHomeLanguage();
	t.after(() => {
		language.destroy();
		window.happyDOM.abort();
		for (const [key, descriptor] of originals) {
			if (descriptor) Object.defineProperty(globalThis, key, descriptor);
			else Reflect.deleteProperty(globalThis, key);
		}
	});
    const translated = [...window.document.querySelectorAll<HTMLElement>('[data-i18n]')];
    const english = translated.map(element => element.tagName === 'META' ? element.getAttribute('content') : element.textContent);
    const image = window.document.querySelector('img[data-i18n-alt]')!;
    const englishAlt = image.getAttribute('alt');
    const toggle = window.document.querySelector<HTMLButtonElement>('[data-language-toggle]')!;
	toggle.click();
	assert.equal(toggle.getAttribute('aria-expanded'), 'true');
	window.document.querySelector<HTMLButtonElement>('[data-language-choice="zh-CN"]')!.click();
	assert.equal(toggle.getAttribute('aria-expanded'), 'false');
	assert.equal(window.document.activeElement, toggle);
	assert.equal(window.document.documentElement.lang, 'zh-CN');
	assert.equal(window.document.querySelector('[aria-current=page]')?.textContent, '首页');
	assert.equal(toggle.getAttribute('aria-label'), '选择语言');
	assert.match(window.document.title, /面向/);
	assert.match(window.document.querySelector('meta[name=description]')!.getAttribute('content')!, /GPU/);
	assert.equal(window.document.querySelector('.eyebrow'), null);
	assert.equal(window.document.querySelector('[data-i18n=summary]')?.textContent, '面向 WebGPU 与 wgpu 的可组合 FrameGraph。');
	assert.equal(window.document.querySelector('[data-i18n=value]')?.textContent, '自主构建渲染功能，组合不同 GPU 系统，看清每一帧的执行过程。');
	assert.equal(window.document.querySelector('[data-i18n=validationTitle]')?.textContent, '资源管理');
	assert.match(window.document.querySelector('[data-i18n=inspectionDescription]')!.textContent, /看清每一帧/);
	assert.equal(window.document.querySelector('.cover-story-marker')?.getAttribute('href'), './playground/?example=refractive-flow&panel=inspector');
	assert.equal(window.document.querySelector('.cover-story-marker')?.getAttribute('aria-label'), '探索此示例');
	assert.equal(window.document.querySelector('[data-i18n=explore]')?.textContent, '探索');
	assert.equal(window.localStorage.getItem('zenfg-language'), 'zh-CN');
    translated.forEach((element, index) => {
        const value = element.tagName === 'META' ? element.getAttribute('content') : element.textContent;
        assert.ok(value?.trim(), 'translated content is present');
        if (value === english[index]) assert.match(value!, /^(?:GitHub|ZenFG|Reference Renderer|TypeGPU|SNAPSHOT|Snapshot|Inspector|TypeScript)/);
    });
    assert.notEqual(image.getAttribute('alt'), englishAlt);
    language.restore();
	assert.equal(window.document.documentElement.lang, 'zh-CN');
	toggle.click();
	window.document.querySelector<HTMLButtonElement>('[data-language-choice=en]')!.click();
	assert.equal(window.document.documentElement.lang, 'en');
	assert.equal(window.document.querySelector('[aria-current=page]')?.textContent, 'Home');
	assert.match(window.document.querySelector('[data-i18n=summary]')!.textContent, /composable/);
	assert.equal(window.document.querySelector('[data-i18n=explore]')?.textContent, 'Explore');
	assert.equal(window.document.querySelector('[data-i18n=validationTitle]')?.textContent, 'Resource management');
	const menu = window.document.querySelector<HTMLElement>('#site-language-menu')!;
	const choices = [...window.document.querySelectorAll<HTMLButtonElement>('[data-language-choice]')];
	const key = (value: string) => window.document.activeElement?.dispatchEvent(new window.KeyboardEvent('keydown', { key: value, bubbles: true }));
	toggle.focus(); key('ArrowDown');
	assert.equal(menu.hidden, false);
	assert.equal(window.document.activeElement, choices[0]);
	key('End'); assert.equal(window.document.activeElement, choices[1]);
	key('ArrowDown'); assert.equal(window.document.activeElement, choices[0]);
	key('Escape'); assert.equal(menu.hidden, true); assert.equal(window.document.activeElement, toggle);
	toggle.click();
	window.document.body.dispatchEvent(new window.PointerEvent('pointerdown', { bubbles: true }));
	assert.equal(menu.hidden, true);
	toggle.click(); key('Tab'); assert.equal(menu.hidden, true);
	assert.equal(choices[1]!.getAttribute('aria-checked'), 'true');
	language.destroy();
	toggle.click();
	assert.equal(menu.hidden, true);
	assert.equal(window.document.documentElement.lang, 'en');
});
