import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import test from 'node:test';
import { FrameGraph } from '@zenfg/webgpu';
import { Particles4All } from '../src/Particles4AllFeature.ts';
import { createFakeDevice, createGpuTrace, installWebGpuGlobals } from './fakeWebGpu.ts';

/**
 * Golden data generated by executing the ORIGINAL source at
 * matsuoka-601/Particles4All@58d6fa6d2c50e3f58da5c7a6f9b885ce26c485f0:
 * src/main.js pourStep/pourJitter and its frame slicing loop; src/sim.js
 * step's time-bank prefix and appendFluid's Float32 conversion.
 *
 * The reference run used a 0.4 m cube, spacing 0.05, support 0.1,
 * 20 initial particles and a 20-particle injection budget, gravity 9.81,
 * nozzle width 0.1, height 0.7, tilt 30 degrees, speed 2.4, and seed 22222.
 * No migration code was used to produce these expected values. Each hash
 * covers every original Float32 position and velocity, then density and zero
 * initialization packed per batch in the graph upload's pos/vel/rho/zero order.
 * Fixtures stay local and do not require GitHub access during tests.
 */
const POUR_FRAMES = [
    { raw: 0.004, scale: 1, steps: 0, bank: 0.004, count: 20, bytes: 0, hash: null },
    { raw: 0.008, scale: 0.5, steps: 0, bank: 0.008, count: 20, bytes: 0, hash: null },
    { raw: 0.025, scale: 1.25, steps: 4, bank: 0.005916666666666667, count: 28, bytes: 416,
        hash: '41d1e418a490cc24f952127e2ca16e02de7a0b82275efae4ea01e43aeb0bc405',
        position: [0.16732816398143768, 0.2447015345096588, 0.17501875758171082, 1],
        velocity: [2.078460931777954, -1.281749963760376, 0, 0] },
    { raw: 0.05, scale: 2, steps: 12, bank: 0.005916666666666667, count: 40, bytes: 624,
        hash: '6dea63f0f25af15853d1589f90573b7e7670a432c59be4e343ad6dbb1b8ed599',
        position: [0.16298305988311768, 0.24726994335651398, 0.17499768733978271, 1],
        velocity: [2.078460931777954, -1.261312484741211, 0, 0] },
    { raw: 0.009, scale: 0.75, steps: 1, bank: 0.004333333333333333, count: 40, bytes: 0, hash: null },
    { raw: 0.02, scale: 1, steps: 2, bank: 0.007666666666666665, count: 40, bytes: 0, hash: null },
    { raw: 0.06, scale: 1, steps: 6, bank: 0.007666666666666669, count: 40, bytes: 0, hash: null },
];

// Original Sim.step with main.js's raw-gap cap applied BEFORE timeScale.
const TIMING_FRAMES = [
    { raw: 0.004, scale: 1, base: 2, steps: 0, bank: 0.004, advanced: 0 },
    { raw: 0.008, scale: 0.5, base: 2, steps: 0, bank: 0.008, advanced: 0 },
    { raw: 0.025, scale: 1.25, base: 2, steps: 4, bank: 0.005916666666666667, advanced: 0.03333333333333333 },
    { raw: 0.05, scale: 2, base: 2, steps: 12, bank: 0.005916666666666667, advanced: 0.1 },
    { raw: 0.009, scale: 0.75, base: 4, steps: 3, bank: 0.00016666666666666566, advanced: 0.0125 },
    { raw: 0.02, scale: 1, base: 4, steps: 4, bank: 0.0034999999999999996, advanced: 0.016666666666666666 },
    { raw: 0.06, scale: 1, base: 1, steps: 3, bank: 0.003500000000000003, advanced: 0.05 },
    { raw: 0, scale: 2, base: 1, steps: 0, bank: 0.003500000000000003, advanced: 0 },
    { raw: 0.5, scale: 2, base: 8, steps: 49, bank: 0.0014166666666666772, advanced: 0.10208333333333333 },
];

function fixture() {
    const restore = installWebGpuGlobals();
    const trace = createGpuTrace();
    const device = createFakeDevice(trace);
    const graph = new FrameGraph(device);
    const workload = new Particles4All({ device, viewport: { width: 80, height: 40 }, outputFormat: 'bgra8unorm' });
    workload.applyImportedSettings({
        ...workload.getSettings(), displayMode: 'particles', substeps: 2, iterations: 2, timeScale: 1,
        pourSpeed: 2.4, pourWidth: 0.1, pourHeight: 0.7, pourTilt: 30, gravity: 9.81,
    }, { targetParticleCount: 20, spacing: 0.05, box: [0.4, 0.4, 0.4], bodies: [], bodySize: 0 });
    const sim = (workload as unknown as { native: { sim: { timeBank?: number; lastAdvanced?: number; lastSubsteps?: number } } }).native.sim;
    const frame = (deltaTime: number) => {
        const recording = graph.beginFrame();
        const color = recording.importSwapchainTexture(device.createTexture({
            format: 'bgra8unorm', size: [80, 40], usage: GPUTextureUsage.RENDER_ATTACHMENT,
        }));
        recording.markPresent(color);
        const pending = workload.recordFrameGraph(recording, { color, deltaTime });
        const compiled = recording.compile({ report: true });
        compiled.execute({ afterSubmit() { pending.commit(); } });
        return compiled.compilationReport;
    };
    return { workload, trace, sim, frame, dispose() { workload.dispose(); graph.destroy(); restore(); } };
}

test('graph injection payload reproduces original nozzle, gravity, jitter and budget across real frame slices', async () => {
    const run = fixture();
    try {
        assert.equal(run.workload.getStats().fluidParticleCount, 20);
        run.workload.togglePour();
        for (const expected of POUR_FRAMES) {
            run.workload.setSettings({ timeScale: expected.scale });
            const beforeWrites = run.trace.bufferWrites.length;
            run.frame(expected.raw);
            const uploads = run.trace.bufferWrites.slice(beforeWrites).filter(write => write.label.startsWith('particles4all.pour-upload.'));
            assert.equal(run.sim.lastSubsteps, expected.steps);
            assert.ok(Math.abs((run.sim.timeBank ?? 0) - expected.bank) < 1e-12);
            assert.equal(run.workload.getStats().fluidParticleCount, expected.count);
            assert.equal(run.workload.getStats().pourRemaining, 40 - expected.count);
            if (expected.hash === null) assert.deepEqual(uploads, []);
            else {
                assert.equal(uploads.length, 1);
                const upload = uploads[0]!;
                assert.equal(upload.size, expected.bytes);
                assert.equal(upload.bytes.byteLength, expected.bytes, 'the small fixture retains the entire payload');
                assert.equal(createHash('sha256').update(upload.bytes).digest('hex'), expected.hash);
                const floats = new Float32Array(upload.bytes.buffer, upload.bytes.byteOffset, upload.bytes.byteLength / 4);
                assert.deepEqual(Array.from(floats.slice(0, 4)), expected.position);
                assert.deepEqual(Array.from(floats.slice(16, 20)), expected.velocity);
            }
            await Promise.resolve();
        }
    } finally { run.dispose(); }
});

test('committed frame schedules match original time-bank golden data across time scales and substep changes', async () => {
    const run = fixture();
    try {
        for (const expected of TIMING_FRAMES) {
            run.workload.setSettings({ timeScale: expected.scale, substeps: expected.base });
            const report = run.frame(expected.raw);
            assert.equal(report.nodes.filter(node => node.label?.endsWith('.predict')).length, expected.steps);
            assert.equal(run.sim.lastSubsteps, expected.steps);
            assert.ok(Math.abs((run.sim.timeBank ?? 0) - expected.bank) < 1e-12);
            assert.ok(Math.abs((run.sim.lastAdvanced ?? 0) - expected.advanced) < 1e-12);
            await Promise.resolve();
        }
    } finally { run.dispose(); }
});
